---
version: "3"

services:
  db:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
#      MONGO_INITDB_DATABASE: speedtest-app
    ports:
      - "27018:27017"


  server:
    build:
      context: ./server
    user: "node"
    working_dir: /app
    volumes:
    - ./server:/app
    command: "npm start"
    ports:
      - '8088:3000'
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: speedtest-app
      ES_URL: 'http://es01:9200'
    depends_on:
      - db
      - es01

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es01
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  app:
    image: 'node:12.16.1-alpine'
    user: "node"
    working_dir: /app
    volumes:
      - ./app:/app
    command: "npm start"
    ports:
      - '4200:4200'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200


volumes:
  data01:
    driver: local



